# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

compatibility_date = "2025-10-08"
main = "src/index.ts"
name = "web-perf-report-cf"
upload_source_maps = true

[[d1_databases]]
binding = "DB"
database_name = "web-perf-db"
database_id = "0d3e24a9-f5b1-416e-bf4a-60cebe36a646"
remote = true

[[durable_objects.bindings]]
name = "PAGE_SPEED"
class_name = "PageSpeedDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PageSpeedDurableObject"]

[observability]
enabled = true

[[r2_buckets]]
bucket_name = "api-results"
binding = "RESULTS_BUCKET"
remote = true

# Smart Placement
# Docs: https://developers.cloudflare.com/workers/configuration/smart-placement/#smart-placement
# placement = { mode = "smart" }

# Bindings
# Bindings allow your Worker to interact with resources on the Cloudflare Developer Platform, including
# databases, object storage, AI inference, real-time communication and more.
# https://developers.cloudflare.com/workers/runtime-apis/bindings/

# Environment Variables
# https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# vars = { MY_VARIABLE = "production_value" }

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/
# assets = { directory = "./public/", binding = "ASSETS" }

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# services = [{ binding = "MY_SERVICE", service = "my-service" }]
